---
connections:
    - host:
      user:
      driver:
      password_file:
      databases:
          - name:
            exclude_tables:

encryption:
    type: gpg
    config:
        recipient: ''
        sign: true
        key_file:

storage:
    type: s3
    config:
        region:
        bucket:
        prefix:
        key:
        secret: ''

rotation:
    daily_backups: 14
    weekly_backup_day: 1
    weekly_backups: 10
    monthly_backup_day: 1
    monthly_backups: 12

mailer:
    host: 127.0.0.1
    port: 25
    from: db-backup@test.dev
    to: tomadam@instantiate.co.uk
    subject: DB Backup Test Error

log:
    file: log/db-backup.log
