#!/usr/bin/env php
<?php
/*
 * This file is part of the DB Backup utility.
 *
 * (c) Tom Adam <tomadam@instantiate.co.uk>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

require __DIR__.'/vendor/autoload.php';

use Instantiate\DatabaseBackup\ConsoleCommand\DbBackupCommand;
use Symfony\Component\Console\Application;

$application = new Application('db-backup');

$command = new DbBackupCommand();
$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();
