#!/usr/bin/env php
<?php
/*
 * This file is part of the DB Backup utility.
 *
 * (c) Tom Adam <tomadam@instantiate.co.uk>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

require 'vendor/autoload.php';

use Instantiate\DatabaseBackup\Console\Application;

$application = new Application();
$application->run();
